Add Solr String To String Array Flexibility #137
NASA-PDS/portal-wp pull request #146
Opened 2024-12-17 21:31 UTC by eddiesarevalo

## 🗒️ Summary
As solr is being developed some types change between strings or string arrays. This pull request adds an expected type that the client will expect from solr. It will then convert all values to arrays and use that type instead. This way it won't break the client due to unexpected type if solr types suddenly change.

## ⚙️ Test Data and/or Report
Run normally. All values will look the same. Tested build process is successful.

## ♻️ Related Issues
fixes #137

2024-12-18 19:51 UTC, jordanpadams requested changes

2024-12-18 19:51 UTC, jordanpadams commented on apps/frontend/src/pages/search/searchUtils.ts
> +        if(docExpected['form-instrument-type']){
@eddiesarevalo is there are a reason we are using "form-instrument-type" here in stead of "instrument_type". I don't know how form-instrument-type is being formed so it may or may not be correct. Same goes for instrument host and investigation below. i would look at `instrument_host_name`, `instrument_host_ref`, `investigation_name`, `investigation_ref` for these values.

2024-12-18 19:52 UTC, jordanpadams commented
Also, SonarQube recommends simplifying your algorithm. Not required that get fixed, but may be worth taking a look at for next time.

2025-01-03 22:53 UTC, eddiesarevalo commented on apps/frontend/src/pages/search/searchUtils.ts
> +        if(docExpected['form-instrument-type']){
Hello @jordanpadams ! `form-instrument-type` and `form-investigation` are only referenced in the Solr response model. They don’t get used or displayed in the app but they are possible values in the json that is returned that is why they are included here.

`instrument_host_name` does get used in instrument host and instrument portal types. At this location:

<img width="726" alt="Screenshot 2025-01-03 at 2 42 03 PM" src="https://github.com/user-attachments/assets/b30d8b75-33d2-4a01-ac49-098fb7d47e44" />

The latest commit now shows instrument_host_name instead.

2025-01-07 17:37 UTC, jordanpadams commented on apps/frontend/src/pages/search/searchUtils.ts
> +        if(docExpected['form-instrument-type']){
@eddiesarevalo copy that. We should remove form-instrument-type and form-investigation from being referenced anywhere in the code. It may be removed from the index in the future and may cause a bit of confusion? My two cents anyways. I am OK with moving forward with this if you would like.

2025-01-09 21:28 UTC, anilnatha approved these changes
Approving on the condition that we are removing the `form-instrument-type` and `form-investigation` fields as Jordan mentioned in another comment.

2025-01-10 00:17 UTC, eddiesarevalo commented
`form-instrument-type` and `form-investigation` have been removed.

2025-01-10 00:21 UTC, anilnatha commented
Thanks for cleaning that up @eddiesarevalo

2025-01-16 17:41 UTC, merged